### ISSUE TITLE
[publish] find a way to publish the example

### ISSUE THREAD

**Issue by JanKoehnlein** [eclipse/sprotty-vscode#18]
The current lerna-based build allows to compile and test the example with the source version of the framework packages, but it actually disables publishing the example to the VS Code marketplace.

It's likely we need a separate build to make that possible.

**Comment by FalseProtagonist** [comment]
The example is published on the VSCode marketplace, under state-example, so how was that accomplished?

**Comment by JanKoehnlein** [comment]
Run `vsce  publish` in the `extenison` directory. Please refer tot he VS Code docs for details (set up MS account, create token etc)

**Comment by JanKoehnlein** [comment]
The config that has made this possible has been deleted. We should restore it.
