### ISSUE TITLE
[Question] Custom Notifications 

### ISSUE THREAD

**Issue by Erlix322** [eclipse/sprotty-vscode#49]
Hi I'm a little bit confused about handling server to client communication. 

What I'd like to achieve is to send a message which needs to be handled by the language client. 

I imagined it is at easy as that but I'm not able to send anything custom to the client.

For example in the command service on the server side
```
public class CommandService implements IExecutableCommandService {
	
	
	@Override
	public List<String> initialize() {
		return Lists.newArrayList("mycommand.run");
	}

	@Override
	public Object execute(ExecuteCommandParams params, ILanguageServerAccess access, CancelIndicator cancelIndicator) {
		
		//Some server stuff going on here
               .....
		
                //What I'd like to do (the function is made up but show what I'd like to do)
		foo.sendNotificationToClient("/mycustomendpoint", "Message");
		
		return "works";
	}

}
```  

Client side
```
extension.languageClient.onNotification("/custom/Message", ()=> {
        show a message or open a webview
})
```

**Comment by spoenemann** [comment]
It seems your question rather belongs to the [LSP4J](https://github.com/eclipse/lsp4j) project. You can add custom messages with LSP4J by providing a custom remote interface: Pass a subinterface of `LanguageClient` to `setRemoteInterface` of the `Launcher.Builder` and annotate the new method with `@JsonNotification`.
